services:
  web:
    build:
      context: ./webapp
    ports:
      - "127.0.0.1:4444:4444"
    volumes:
      - ./webapp/public:/app/public
    environment:
      - PORT=4444
    restart: unless-stopped

