version: '3.8'

services:
  web:
    build:
      context: ./webapp
    ports:
      - "4444:4444"
    volumes:
      - ./webapp/public:/app/public
    environment:
      - PORT=4444
    restart: unless-stopped

